import pygame

#Downloading pictures that will be used in the calendar
def download_pictures(self):

    self.background = pygame.image.load("background.png")
    self.background = pygame.image.load("background2.png")
    self.mouse = pygame.image.load("mouse.png")
    self.not_time_yet = pygame.image.load("not_time_yet.png")

    self.sound_button_on = pygame.image.load("sound_button_on.png")
    self.sound_button_off = pygame.image.load("sound_button_off.png")
    self.music_button_on = pygame.image.load("music_button_on.png")
    self.music_button_off = pygame.image.load("music_button_off.png")
    self.sound_button_on_hover_over = pygame.image.load("sound_button_on_hover_over.png")
    self.sound_button_off_hover_over = pygame.image.load("sound_button_off_hover_over.png")
    self.music_button_on_hover_over = pygame.image.load("music_button_on_hover_over.png")
    self.music_button_off_hover_over = pygame.image.load("music_button_off_hover_over.png")

    self.background_real_cubes_lid1 = pygame.image.load("background_real_cubes_lid1.png")
    self.background_real_cubes_lid2 = pygame.image.load("background_real_cubes_lid2.png")
    self.background_real_cubes_lid3 = pygame.image.load("background_real_cubes_lid3.png")
    self.background_real_cubes_lid4 = pygame.image.load("background_real_cubes_lid4.png")
    self.background_real_cubes_lid5 = pygame.image.load("background_real_cubes_lid5.png")
    self.background_real_cubes_lid6 = pygame.image.load("background_real_cubes_lid6.png")
    self.background_real_cubes_lid7 = pygame.image.load("background_real_cubes_lid7.png")
    self.background_real_cubes_lid8 = pygame.image.load("background_real_cubes_lid8.png")
    self.background_real_cubes_lid9 = pygame.image.load("background_real_cubes_lid9.png")
    self.background_real_cubes_lid10 = pygame.image.load("background_real_cubes_lid10.png")
    self.background_real_cubes_lid11 = pygame.image.load("background_real_cubes_lid11.png")
    self.background_real_cubes_lid12 = pygame.image.load("background_real_cubes_lid12.png")
    self.background_real_cubes_lid13 = pygame.image.load("background_real_cubes_lid13.png")
    self.background_real_cubes_lid14 = pygame.image.load("background_real_cubes_lid14.png")
    self.background_real_cubes_lid15 = pygame.image.load("background_real_cubes_lid15.png")
    self.background_real_cubes_lid16 = pygame.image.load("background_real_cubes_lid16.png")
    self.background_real_cubes_lid17 = pygame.image.load("background_real_cubes_lid17.png")
    self.background_real_cubes_lid18 = pygame.image.load("background_real_cubes_lid18.png")
    self.background_real_cubes_lid19 = pygame.image.load("background_real_cubes_lid19.png")
    self.background_real_cubes_lid20 = pygame.image.load("background_real_cubes_lid20.png")
    self.background_real_cubes_lid21 = pygame.image.load("background_real_cubes_lid21.png")
    self.background_real_cubes_lid22 = pygame.image.load("background_real_cubes_lid22.png")
    self.background_real_cubes_lid23 = pygame.image.load("background_real_cubes_lid23.png")
    self.background_real_cubes_lid24 = pygame.image.load("background_real_cubes_lid24.png")

    self.background_real_cubes_lid1_hover_over = pygame.image.load("background_real_cubes_lid1_hover_over.png")
    self.background_real_cubes_lid2_hover_over = pygame.image.load("background_real_cubes_lid2_hover_over.png")
    self.background_real_cubes_lid3_hover_over = pygame.image.load("background_real_cubes_lid3_hover_over.png")
    self.background_real_cubes_lid4_hover_over = pygame.image.load("background_real_cubes_lid4_hover_over.png")
    self.background_real_cubes_lid5_hover_over = pygame.image.load("background_real_cubes_lid5_hover_over.png")
    self.background_real_cubes_lid6_hover_over = pygame.image.load("background_real_cubes_lid6_hover_over.png")
    self.background_real_cubes_lid7_hover_over = pygame.image.load("background_real_cubes_lid7_hover_over.png")
    self.background_real_cubes_lid8_hover_over = pygame.image.load("background_real_cubes_lid8_hover_over.png")
    self.background_real_cubes_lid9_hover_over = pygame.image.load("background_real_cubes_lid9_hover_over.png")
    self.background_real_cubes_lid10_hover_over = pygame.image.load("background_real_cubes_lid10_hover_over.png")
    self.background_real_cubes_lid11_hover_over = pygame.image.load("background_real_cubes_lid11_hover_over.png")
    self.background_real_cubes_lid12_hover_over = pygame.image.load("background_real_cubes_lid12_hover_over.png")
    self.background_real_cubes_lid13_hover_over = pygame.image.load("background_real_cubes_lid13_hover_over.png")
    self.background_real_cubes_lid14_hover_over = pygame.image.load("background_real_cubes_lid14_hover_over.png")
    self.background_real_cubes_lid15_hover_over = pygame.image.load("background_real_cubes_lid15_hover_over.png")
    self.background_real_cubes_lid16_hover_over = pygame.image.load("background_real_cubes_lid16_hover_over.png")
    self.background_real_cubes_lid17_hover_over = pygame.image.load("background_real_cubes_lid17_hover_over.png")
    self.background_real_cubes_lid18_hover_over = pygame.image.load("background_real_cubes_lid18_hover_over.png")
    self.background_real_cubes_lid20_hover_over = pygame.image.load("background_real_cubes_lid20_hover_over.png")
    self.background_real_cubes_lid21_hover_over = pygame.image.load("background_real_cubes_lid21_hover_over.png")
    self.background_real_cubes_lid22_hover_over = pygame.image.load("background_real_cubes_lid22_hover_over.png")
    self.background_real_cubes_lid23_hover_over = pygame.image.load("background_real_cubes_lid23_hover_over.png")
    self.background_real_cubes_lid24_hover_over = pygame.image.load("background_real_cubes_lid24_hover_over.png")